mmmain:	  DateTime.o Comparable.o DataUsuario.o DataColaborador.o DataErrores.o DataAccion.o DataInformacionUsuario.o Usuario.o UsuarioControlador.o RecursoControlador.o Comentario.o Colaborador.o ManejadorUsuario.o Fabrica.o main.o ManejadorUsuarioControlador.o ManejadorRecursoControlador.o
	g++   DateTime.o Comparable.o DataUsuario.o DataColaborador.o DataErrores.o DataAccion.o DataInformacionUsuario.o Usuario.o UsuarioControlador.o RecursoControlador.o Comentario.o Colaborador.o ManejadorUsuario.o Fabrica.o main.o ManejadorUsuarioControlador.o ManejadorRecursoControlador.o -o main

DateTime.o:	DateTime.cpp	DateTime.h
	g++ -c DateTime.cpp -I.

DataUsuario.o:	DataUsuario.cpp	DataUsuario.h
	g++ -c DataUsuario.cpp -I.

DataColaborador.o:	DataColaborador.cpp	DataColaborador.h
	g++ -c DataColaborador.cpp -I.

DataErrores.o:	DataErrores.cpp	DataErrores.h
	g++ -c DataErrores.cpp -I.


DataAccion.o:	DataAccion.cpp	DataAccion.h
	g++ -c DataAccion.cpp -I.

main.o:	main.cpp 
	g++ -c main.cpp -I.

Fabrica.o: Fabrica.cpp Fabrica.h
	g++ -c Fabrica.cpp -I.

Comparable.o:	Comparable.cpp	Comparable.h
	g++ -c Comparable.cpp -I.

DataInformacionUsuario.o: DataInformacionUsuario.cpp DataInformacionUsuario.h
	g++ -c DataInformacionUsuario.cpp -I.

Usuario.o:	Usuario.cpp	Usuario.h
	g++ -c Usuario.cpp -I.

UsuarioControlador.o:	UsuarioControlador.cpp	UsuarioControlador.h
	g++ -c UsuarioControlador.cpp -I.

ManejadorUsuario.o: ManejadorUsuario.cpp ManejadorUsuario.h
	g++ -c ManejadorUsuario.cpp -I.

RecursoControlador.o:	RecursoControlador.cpp	RecursoControlador.h
	g++ -c RecursoControlador.cpp -I.

Comentario.o: Comentario.cpp Comentario.h
	g++ -c Comentario.cpp -I.

Colaborador.o: Colaborador.cpp Colaborador.h
	g++ -c Colaborador.cpp -I.

ManejadorUsuarioControlador.o: ManejadorUsuarioControlador.cpp ManejadorUsuarioControlador.h
	g++ -c ManejadorUsuarioControlador.cpp -I.

ManejadorRecursoControlador.o: ManejadorRecursoControlador.cpp ManejadorRecursoControlador.h
	g++ -c ManejadorRecursoControlador.cpp -I.

limpiar:
	rm *.o